### PR TITLE
Add support for hvac-units API endpoint

### PR DESCRIPTION
**Pull request by smcpeck**
Hey, @RobertD502. I have forked your two repos for this and I feel this is the least breaking one since it doesn't change the current behavior of your Helper at all. So I wanted to get your eyes on it.

I will say that I am new to Home Assistant and don't have a proper development environment setup, so there are likely some issues here where things just don't line up right. Was hoping to get your assistance in getting this properly ironed out.

I have two mini-splits setup with Pucks, so we can definitely test this in a full blown environment to make sure everything is flowing through all the layers properly.

Would love any initial feedback you might have.
Cheers!

### CODE REVIEW

**Comment by RobertD502** [comment]
@smcpeck Thanks for doing this! I've been meaning to add mini split control and your PR pushed me to work on it a bit. I made some changes to your code + added more to give us full control of mini split units. Next up I'll work on getting code written up on the Home Assistant side. I've completely rewritten the Home Assistant side already (locally) and will be creating a new release once I get mini split control integrated as well. Prior to that, I'll be pushing the changes to a dev branch and would love for you to test it if you have some time.

**Comment by smcpeck** [comment]
Glad this was useful to an extent. Definitely happy to add the repo/branch once you have your rewrite in order. Also happy to contribute a bit on said branch if you'd like. 🍻

**Comment by RobertD502** [comment]
@smcpeck I noticed in your fork of the HA integration you created a switch entity for the mini-split. Just wanted to let you know that the final entity will be a climate entity allowing users to set the mode, temperature, fan speed, etc.

**Comment by smcpeck** [comment]
@RobertD502 That 100% makes sense. I was trying to do a quick hit just to let me turn the mini-split on/off.  Full control would be ideal and amazing. Cheers!

**Comment by RobertD502** [comment]
@smcpeck rewritten flair home assistant integration code has been added to the repo's 'dev' branch. Be sure to replace all of the files in your flair folder with those in the dev branch (you no longer need the services file).
Let me know if you come across any problems while using the new entities and, of course, mini split control.

Just FYI: there are major changes (new entities and renamed entities), so, if you have any automations that use the Flair integration, make sure that they are still valid and make changes as necessary.

**Pull request merged**
